### ISSUE TITLE
XFCE Terminal menubar elements - increase spacing please.

### ISSUE THREAD

**Issue by antoniotrkdz** [mustafaozguner/solarized-dark-xfce#2]
In the XFCE terminal the elements of the menubar are too close to each other as per screenshot below:
![image](https://user-images.githubusercontent.com/18493541/39221761-34c01a62-4839-11e8-94e9-c2374bfd214a.png)
Please increase the spacing.

P.S.: The theme is very nice.

**Comment by 0zguner** [comment]
@antoniotrkdz sorry for late return :( I would accept your PR if you want to work on this
